# Generated by Django 5.2.3 on 2025-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
